configuration:
- Release
before_build:
- cmd: >-
    git clone https://github.com/SFML/SFML.git

    cd SFML

    mkdir install

    mkdir build

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_SHARED_LIBS=FALSE -DSFML_USE_STATIC_STD_LIBS=TRUE ..

    msbuild INSTALL.vcxproj

    cd ../../

    git clone https://github.com/eXpl0it3r/SmallGameEngine.git

    cd SmallGameEngine

    mkdir SmallGameEngine

    mkdir build

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=../SmallGameEngine -DSMALLGAMEENGINE_STATIC_STD_LIBS=TRUE -DSFML_STATIC_LIBS=TRUE -DCMAKE_MODULE_PATH=C:/projects/smallgameengine/SFML/install/cmake/Modules -DSFML_ROOT=C:/projects/smallgameengine/SFML/install ..
build:
  project: SmallGameEngine/build/INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd ../../

    7z a SmallGameEngine-Windows.zip C:/projects/smallgameengine/SmallGameEngine/SmallGameEngine -r
artifacts:
- path: SmallGameEngine-Windows.zip
  name: SmallGameEngine-Windows
deploy:
  release: SmallGameEngine-Windows
  description: 'SmallGameEngine Windows Release'
  provider: GitHub
  artifact: SmallGameEngine-Windows.zip
  auth_token:
    secure: n5YYrvLk5Ft1l7lPmJtLHeS6CzP9Ug76cpuG57EzDFatUHa376mwi2US3eevImQ9I09KFtcFOFpqSphEvyvtIVhMsGkhm89kJn/inSmBOkmWWasN/m2chDTic0SnfoiwbYozIfqCJ5PIW+nRgwGY65np4GInnixcfaK5giaGBrI=
  on:
    branch: master
